#!/usr/bin/env python3
"""
scripts/reproduce.py — Reproduction script for experiments.

Provides exact commands to reproduce all experimental results.
"""

import sys
from pathlib import Path


def print_section(title: str):
    """Print a section header."""
    print("\n" + "=" * 70)
    print(title)
    print("=" * 70)


def main():
    """Print reproduction instructions."""

    print_section("RAG PIPELINE — EXPERIMENT REPRODUCTION GUIDE")

    print("\n📋 PREREQUISITES")
    print("-" * 70)
    print("1. Python 3.11+")
    print("2. OpenAI API key (for LLM generation)")
    print("3. Sufficient compute for embeddings (CPU or GPU)")
    print("4. Real financial documents (SEC filings)")

    print("\n📦 INSTALLATION")
    print("-" * 70)
    print("```bash")
    print("# Clone repository")
    print("git clone https://github.com/arraimal70-code/RAG-Pipeline.git")
    print("cd RAG-Pipeline")
    print()
    print("# Create virtual environment")
    print("python -m venv .venv")
    print("source .venv/bin/activate  # Linux/Mac")
    print("# .venv\\Scripts\\activate  # Windows")
    print()
    print("# Install dependencies")
    print("pip install -r requirements.txt")
    print()
    print("# Configure environment")
    print("cp .env.example .env")
    print("# Edit .env and add your OPENAI_API_KEY")
    print("```")

    print("\n📄 DOCUMENT PREPARATION")
    print("-" * 70)
    print("```bash")
    print("# Create documents directory")
    print("mkdir -p data/documents")
    print()
    print("# Obtain SEC filings from EDGAR (https://www.sec.gov/edgar)")
    print("# Example: Download 10-K filings for Apple, Microsoft, Amazon")
    print("# Place PDFs in data/documents/")
    print()
    print("# Validate benchmark")
    print("python scripts/validate_benchmark.py benchmarks/benchmark_v2.json")
    print("```")

    print("\n🔄 INGESTION")
    print("-" * 70)
    print("```bash")
    print("# Ingest all documents")
    print("python -m src.pipeline ingest data/documents/")
    print()
    print("# Or ingest individual documents")
    print("python -m src.pipeline ingest data/documents/apple_10k_2023.pdf")
    print("```")

    print("\n🧪 RUNNING EXPERIMENTS")
    print("-" * 70)
    print("```bash")
    print("# Run all experiments")
    print("python experiments/runner.py")
    print()
    print("# Run specific experiment")
    print("python -c \"")
    print("from experiments.runner import ExperimentRunner, EXPERIMENTS")
    print("runner = ExperimentRunner()")
    print("questions = runner.load_benchmark()")
    print("result = runner.run_experiment('EXP-01_dense_baseline', EXPERIMENTS['EXP-01_dense_baseline'], questions)")
    print("\"")
    print()
    print("# View results")
    print("cat experiments/results/COMPARISON.md")
    print("```")

    print("\n📊 PERFORMANCE MEASUREMENT")
    print("-" * 70)
    print("```bash")
    print("# Measure query latency")
    print("python scripts/measure_performance.py --output performance_report.json")
    print()
    print("# View report")
    print("cat performance_report.json")
    print("```")

    print("\n🧪 RUNNING TESTS")
    print("-" * 70)
    print("```bash")
    print("# Run all tests")
    print("pytest tests/ -v")
    print()
    print("# Run specific test file")
    print("pytest tests/test_integration.py -v")
    print()
    print("# Run with coverage")
    print("pytest tests/ --cov=src --cov-report=html")
    print("```")

    print("\n🔍 QUERYING THE SYSTEM")
    print("-" * 70)
    print("```bash")
    print("# Interactive query")
    print("python -m src.pipeline query \"What was the revenue in 2023?\"")
    print()
    print("# Or use Python API")
    print("python -c \"")
    print("from src.pipeline import query")
    print("response = query('What was the revenue in 2023?')")
    print("print(response.answer)")
    print("print(f'Confidence: {response.confidence:.2f}')")
    print("print(f'Citations: {len(response.citations)}')")
    print("\"")
    print("```")

    print("\n🐳 DOCKER")
    print("-" * 70)
    print("```bash")
    print("# Build Docker image")
    print("docker build -t rag-pipeline .")
    print()
    print("# Run container")
    print("docker run -p 8000:8000 --env-file .env rag-pipeline")
    print()
    print("# API will be available at http://localhost:8000")
    print("```")

    print("\n📈 EXPERIMENT LIST")
    print("-" * 70)
    print("The following experiments are defined:")
    print()
    print("Retrieval Strategy:")
    print("  EXP-01: Dense baseline")
    print("  EXP-02: BM25 baseline")
    print("  EXP-03: Hybrid RRF")
    print("  EXP-04: Dense-heavy hybrid")
    print("  EXP-05: Lexical-heavy hybrid")
    print("  EXP-06: Adaptive hybrid")
    print()
    print("Chunking:")
    print("  EXP-07a: Fixed chunking")
    print("  EXP-07b: Sentence chunking")
    print("  EXP-07c: Recursive chunking")
    print("  EXP-07d: Structure-aware chunking")
    print()
    print("Components:")
    print("  EXP-09: Reranking impact")
    print("  EXP-10: Top-K sensitivity")
    print("  EXP-11: Evidence sufficiency")
    print("  EXP-12: Citation validation")
    print("  EXP-13: Contradiction detection")
    print()
    print("Ablations:")
    print("  EXP-ABL-1: No BM25")
    print("  EXP-ABL-2: No Dense")
    print("  EXP-ABL-3: No Adaptive")
    print("  EXP-ABL-4: No Evidence Check")
    print("  EXP-ABL-5: No Reranker")
    print()
    print("Full System:")
    print("  EXP-19: Full optimized system")

    print("\n📊 EXPECTED OUTPUT")
    print("-" * 70)
    print("After running experiments, you should have:")
    print("  • experiments/results/*.json — Individual experiment results")
    print("  • experiments/results/COMPARISON.md — Comparison table")
    print("  • performance_report.json — Performance measurements")
    print("  • logs/trace_*.json — Query traces")

    print("\n⚠️  IMPORTANT NOTES")
    print("-" * 70)
    print("1. Results depend on the quality of your document set")
    print("2. OpenAI API costs apply for LLM generation")
    print("3. Embedding generation may take time for large document sets")
    print("4. Some experiments require specific document characteristics")
    print("5. Results are NOT pre-populated — you must run experiments")

    print("\n📚 DOCUMENTATION")
    print("-" * 70)
    print("Key documentation files:")
    print("  • README.md — Project overview")
    print("  • docs/ARCHITECTURE.md — System architecture")
    print("  • docs/RESEARCH_QUESTION.md — Research questions")
    print("  • docs/METHODOLOGY.md — Experimental methodology")
    print("  • docs/EXPERIMENTS.md — Experiment descriptions")
    print("  • docs/RESULTS.md — Results (after running experiments)")
    print("  • docs/FINDINGS.md — Findings (after analysis)")
    print("  • docs/LIMITATIONS.md — Known limitations")
    print("  • docs/FINAL_PROJECT_AUDIT.md — Project audit")

    print("\n" + "=" * 70)
    print("For issues or questions, consult the documentation or")
    print("check the project repository for updates.")
    print("=" * 70 + "\n")


if __name__ == "__main__":
    main()
